In [1]:
import pandas as pd
import re
import nltk

In [2]:
df = pd.read_csv("oura_ring4_all_reviews.csv")

Looking at the data we have

In [3]:
df.head()

,review_id,source,rating,title,body,review_date,verified,helpful_votes,scraped_at
0,target_00000,target,5,Loving My Ōura Ring,So far loving my Ōura ring! It’s not been unco...,"18 March, 2026",False,0,2026-03-28T15:37:14Z
1,target_00001,target,5,Useful & Convenient,I bought my Oura ring in store and sized using...,"11 March, 2026",False,0,2026-03-28T15:37:14Z
2,target_00002,target,2,Lasted less than 1 year,I purchased this item in March 2025. Loved it....,"11 March, 2026",False,0,2026-03-28T15:37:14Z
3,target_00003,target,1,(no review title),Stopped working completely after 1.5 years. Ba...,"9 March, 2026",False,0,2026-03-28T15:37:14Z
4,target_00004,target,5,A great investment,I wanted to share my 6-month review of the Our...,"6 March, 2026",False,0,2026-03-28T15:37:14Z

In [4]:
df.columns

Index(['review_id', 'source', 'rating', 'title', 'body', 'review_date',
       'verified', 'helpful_votes', 'scraped_at'],
      dtype='object')

Confirming body column is the text we want to use

In [5]:
df["body"] = df["body"].astype(str)

Turning all of body text into lowercase

In [6]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^\w\s]", "", text)   # remove punctuation
    text = re.sub(r"\d+", "", text)       # remove numbers
    text = re.sub(r"\s+", " ", text).strip()  # remove extra spaces
    return text

In [7]:
df["clean_body"] = df["body"].apply(clean_text)

In [8]:
df[["body", "clean_body"]].head(10)

,body,clean_body
0,So far loving my Ōura ring! It’s not been unco...,so far loving my ōura ring its not been uncomf...
1,I bought my Oura ring in store and sized using...,i bought my oura ring in store and sized using...
2,I purchased this item in March 2025. Loved it....,i purchased this item in march loved it fast f...
3,Stopped working completely after 1.5 years. Ba...,stopped working completely after years battery...
4,I wanted to share my 6-month review of the Our...,i wanted to share my month review of the oura ...
5,Still haven’t received my order. It was suppos...,still havent received my order it was supposed...
6,An expensive piece of crap that only was funci...,an expensive piece of crap that only was funci...
7,I’ve had a ring for just over a year and the b...,ive had a ring for just over a year and the ba...
8,Why did my ring come unsealed. Was it used?,why did my ring come unsealed was it used
9,Thank you to the kind gentleman that helped me...,thank you to the kind gentleman that helped me...

Stopword Removal:

In [9]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Susan
[nltk_data]     Gomez\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

Inspect the full NLTK stopword list to identify which words may impact sentiment, then customize the list by preserving key negation terms. We need to keep ones like "should," "never, "not," etc.

In [10]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

print(sorted(stop_words))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", "he's", 'her', 'here', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'i', "i'd", "i'll", "i'm", "i've", 'if', 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', "should've", 'shouldn', "shouldn't", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", "we've", 'were', 'weren', "weren't", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", "you're", "you've", 'your', 'yours', 'yourself', 'yourselves']

Because we remove punctuation and do not split contractions, words like ‘dont’ and ‘wont’ will be kept anyways because they are not in NLTK's stopword list. The words that are are in the NLTK contain the contraction, like "don't" or "wont't."

We only preserve words that meaningfully affect sentiment or indicate unmet needs, such as negation terms and expectation-based words like ‘should’ and ‘need,’ while removing general grammatical words to reduce noise.

In [11]:
important_words = {"not", "no", "never", "should", "need"} #Words we want to keep
stop_words = stop_words - important_words #Removing words we want to keep from stopword list
print("not" in stop_words)
print("no" in stop_words)
print("never" in stop_words)
print("should" in stop_words)
print("need" in stop_words)

False
False
False
False
False

In [13]:
def remove_stopwords(text):
    return " ".join([word for word in text.split() if word not in stop_words])

df["clean_body"] = df["clean_body"].apply(remove_stopwords)
df[["body", "clean_body"]].head(10)

,body,clean_body
0,So far loving my Ōura ring! It’s not been unco...,far loving ōura ring not uncomfortable not pur...
1,I bought my Oura ring in store and sized using...,bought oura ring store sized using sizers stor...
2,I purchased this item in March 2025. Loved it....,purchased item march loved fast forward march ...
3,Stopped working completely after 1.5 years. Ba...,stopped working completely years battery used ...
4,I wanted to share my 6-month review of the Our...,wanted share month review oura ring considerin...
5,Still haven’t received my order. It was suppos...,still havent received order supposed delivered...
6,An expensive piece of crap that only was funci...,expensive piece crap funcional months lot conn...
7,I’ve had a ring for just over a year and the b...,ive ring year batteries horrible might apply y...
8,Why did my ring come unsealed. Was it used?,ring come unsealed used
9,Thank you to the kind gentleman that helped me...,thank kind gentleman helped questions ring als...

In [14]:
df.to_csv("oura_ring4_all_reviews_preprocessed.csv", index=False)